@GitHubUserInfoDemo_HostAddress = https://localhost:7041

GET {{GitHubUserInfoDemo_HostAddress}}/api/githubuserinfo/pa-p

###

GET {{GitHubUserInfoDemo_HostAddress}}/api/githubuserinfocached/pa-p

###
